<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ParserConstantsTests.fs" />
    <Compile Include="ParserOperatorsTests.fs" />
    <Compile Include="ParserFormulasTests.fs" />
    <Compile Include="ParserCellReferencesTests.fs" />
    <Compile Include="ReferenceResolverTests.fs" />
    <Compile Include="QT4Tests.fs" />
    <Compile Include="EvalVolatileTests.fs" />
    <Compile Include="EvalConstantsTests.fs" />
    <Compile Include="EvalLogicTests.fs" />
    <Compile Include="EvalUnaryTests.fs" />
    <Compile Include="EvalBinaryTests.fs" />
    <Compile Include="EvalRefTests.fs" />
    <Compile Include="EvalFunTests.fs" />
    <Compile Include="WorkbookTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsUnit.xUnit" Version="7.1.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit.v3" Version="4.0.0" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Forecalc.Library\Forecalc.Library.fsproj" />
  </ItemGroup>

</Project>
