---
name: Build and Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-and-test.yml
      - src/**
      - tests/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/build-and-test.yml
      - src/**
      - tests/**

  workflow_dispatch:

env:
  DOTNET_CONFIGURATION: Release

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration $DOTNET_CONFIGURATION --no-restore

      - name: Test
        run: dotnet test --configuration $DOTNET_CONFIGURATION --no-build --verbosity normal
